version: 2.1
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build:
    docker:
      - image: cimg/node:18.17.1-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build-with-machine:
    environment:
      DOCKER_IMAGE: hoangtn4/blog-api
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - add_ssh_keys:
          fingerprints:
            - 'cc:d2:14:d2:ef:5f:8c:a6:08:61:a6:80:43:95:52:5b'
      - run:
          name: Deploy to Server
          command: |
            ssh -oStrictHostKeyChecking=no hoang@1.52.225.62 'sh ./blog/deploy-be.sh'
workflows:
  lint-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - build-with-machine:
          requires:
            - build
